// <auto-generated />
using System;
using DoAnTotNghiep_KS_BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnTotNghiep_KS_BE.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251107034140_Update_DatPhong_Phong_Key")]
    partial class Update_DatPhong_Phong_Key
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int?>("Diem")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaPhong");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.DatPhong", b =>
                {
                    b.Property<int>("MaDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatPhong"));

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhanPhong")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTraPhong")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaDatPhong");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DatPhong");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.DatPhong_Phong", b =>
                {
                    b.Property<int>("MaDatPhong_Phong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatPhong_Phong"));

                    b.Property<int>("MaDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.HasKey("MaDatPhong_Phong");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaDatPhong", "MaPhong")
                        .IsUnique();

                    b.ToTable("DatPhong_Phong");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.HinhAnhPhong", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("MaPhong");

                    b.ToTable("HinhAnhPhong");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.HoanTien", b =>
                {
                    b.Property<int>("MaHoanTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoanTien"));

                    b.Property<int>("MaHuyDatPhong")
                        .HasColumnType("int");

                    b.Property<int?>("MaQuanTri")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoanTien");

                    b.HasIndex("MaHuyDatPhong");

                    b.HasIndex("MaQuanTri");

                    b.ToTable("HoanTien");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.HuyDatPhong", b =>
                {
                    b.Property<int>("MaHuyDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHuyDatPhong"));

                    b.Property<string>("GhiChuLeTan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LyDo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVienDuyet")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayYeuCau")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PhiGiu")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("SoTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenChuTaiKhoan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHuyDatPhong");

                    b.HasIndex("MaDatPhong");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVienDuyet");

                    b.ToTable("HuyDatPhong");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.OTP", b =>
                {
                    b.Property<int>("MaOTP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaOTP"));

                    b.Property<bool>("DaSuDung")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HetHanSau")
                        .HasColumnType("datetime2");

                    b.Property<string>("Loai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MaXacThuc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaOTP");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("OTP");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<int?>("DienTich")
                        .HasColumnType("int");

                    b.Property<decimal?>("GiaMoiDem")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("HuongNhin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTang")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoGiuong")
                        .HasColumnType("int");

                    b.Property<int?>("SoNguoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("SoPhong")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenLoai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaTang");

                    b.HasIndex("SoPhong")
                        .IsUnique()
                        .HasFilter("[SoPhong] IS NOT NULL");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.Phong_TienNghi", b =>
                {
                    b.Property<int>("MaPhongTienNghi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongTienNghi"));

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaTienNghi")
                        .HasColumnType("int");

                    b.HasKey("MaPhongTienNghi");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaTienNghi");

                    b.ToTable("Phong_TienNghi");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.RefreshToken", b =>
                {
                    b.Property<int>("MaRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaRefreshToken"));

                    b.Property<bool>("DaSuDung")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySuDung")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaRefreshToken");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.Tang", b =>
                {
                    b.Property<int>("MaTang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTang"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenTang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTang");

                    b.ToTable("Tang");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<int>("MaDatPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaDatPhong");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.TienNghi", b =>
                {
                    b.Property<int>("MaTienNghi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTienNghi"));

                    b.Property<string>("Icon")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ten")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTienNghi");

                    b.ToTable("TienNghi");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.DanhGia", b =>
                {
                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.NguoiDung", "KhachHang")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.Phong", "Phong")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaPhong");

                    b.Navigation("KhachHang");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.DatPhong", b =>
                {
                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.NguoiDung", "KhachHang")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.DatPhong_Phong", b =>
                {
                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.DatPhong", "DatPhong")
                        .WithMany("DatPhong_Phongs")
                        .HasForeignKey("MaDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.Phong", "Phong")
                        .WithMany("DatPhong_Phongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatPhong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.HinhAnhPhong", b =>
                {
                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.Phong", "Phong")
                        .WithMany("HinhAnhPhongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.HoanTien", b =>
                {
                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.HuyDatPhong", "HuyDatPhong")
                        .WithMany("HoanTiens")
                        .HasForeignKey("MaHuyDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.NguoiDung", "QuanTri")
                        .WithMany("HoanTiens")
                        .HasForeignKey("MaQuanTri")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HuyDatPhong");

                    b.Navigation("QuanTri");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.HuyDatPhong", b =>
                {
                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.DatPhong", "DatPhong")
                        .WithMany("HuyDatPhongs")
                        .HasForeignKey("MaDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.NguoiDung", "KhachHang")
                        .WithMany("HuyDatPhongsKhachHang")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.NguoiDung", "NhanVienDuyet")
                        .WithMany("HuyDatPhongsNhanVien")
                        .HasForeignKey("MaNhanVienDuyet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DatPhong");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVienDuyet");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.OTP", b =>
                {
                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.NguoiDung", "NguoiDung")
                        .WithMany("OTPs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.Phong", b =>
                {
                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.Tang", "Tang")
                        .WithMany("Phongs")
                        .HasForeignKey("MaTang");

                    b.Navigation("Tang");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.Phong_TienNghi", b =>
                {
                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.Phong", "Phong")
                        .WithMany("Phong_TienNghis")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.TienNghi", "TienNghi")
                        .WithMany("Phong_TienNghis")
                        .HasForeignKey("MaTienNghi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");

                    b.Navigation("TienNghi");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.NguoiDung", "NguoiDung")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.ThanhToan", b =>
                {
                    b.HasOne("DoAnTotNghiep_KS_BE.Data.Entities.DatPhong", "DatPhong")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatPhong");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.DatPhong", b =>
                {
                    b.Navigation("DatPhong_Phongs");

                    b.Navigation("HuyDatPhongs");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.HuyDatPhong", b =>
                {
                    b.Navigation("HoanTiens");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DatPhongs");

                    b.Navigation("HoanTiens");

                    b.Navigation("HuyDatPhongsKhachHang");

                    b.Navigation("HuyDatPhongsNhanVien");

                    b.Navigation("OTPs");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.Phong", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DatPhong_Phongs");

                    b.Navigation("HinhAnhPhongs");

                    b.Navigation("Phong_TienNghis");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.Tang", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("DoAnTotNghiep_KS_BE.Data.Entities.TienNghi", b =>
                {
                    b.Navigation("Phong_TienNghis");
                });
#pragma warning restore 612, 618
        }
    }
}
